server:
  port: 8093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: 192.168.192.168
    virtual-host: /gmall
    username: yu
    password: yu
auth:
  jwt:
    publicKeyPath: F:\\IdeaProjects\\gmall\\secret\\rsa.pub
    cookieName: GMALL_TOKEN

alipay:
  app_id: 2016101500692147
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDd/oV3AjbQhLMQOBoFiKkIxZw/C+0pfsrXuh2Fiy/nWd1nUvLu2TagTw+O+dZ6TMgM9YrdKsL+TeGXiyW7vaQtzoRo4GCG7EpGXfEjobb6qxvU5RX53O5bNcWIL48JSEN5fIqJ651ejipZ31CGjPOuBSZTGquxYWI2BdOGaQPgYpa6cop7Qp9CpnW8qEpW5dPlZvq48pkcfuGiRc107n9EmQd+az/VmGjRb++2KLS0GrA0DU4MhjqlPT2AM5kM6tK1Ir8m40+cf774VHPPcNrYUX7qzMbHrzcNMeNWvUO9MLGSMB25IZgp/ikdWMsxthFKIpm00TyVSRkulcuENqEXAgMBAAECggEAKTaigpinooiwUbeIpTRc5WMCgfXt3sFKWUiVSICxsQrO/uq4bT1oVdS3t7yMZAIzNay0TiEtOFcvJZpQtA0eGN75WBsn8ISXuX6hURMpzFnN/fVV4iBxI//Un1btADUpSbmkYryaZ76PAEZkRcaPSuRr3Avcij7hI9RrE84VSSfL8+hytXBApTvbN9/r14Xfiln+NJ/4Ot3lTxmA+XoitbVgn2MXXh/wgANwPMExDQ70CHpJLRQSths2hE/Odl1cmWcZQhgBVet+S9zJxtyIlkeyMiSykiKmpVRB5cG/RFcOgh4m5OuHZ7ae6QaxW9hIoWBPU7TksHfu+aI04QSA4QKBgQD1f7LR3Allmr0HO/2q7wWcFa8R3le+uRw4Tjr5uqFxidYZpwsPEC/Lb63jIxFLiDpb59yz0w3GYNE0RQxHXDrAn5ukFGV8Nv59F2hmBOfuiiFK9nB4ohkvibl1aKo5wXyocK9NgL+GLiQfihtYef/iDrifydI4Wh4AZdXLfASQRwKBgQDnfXBdSZblVhiCxTFJuCwm490ugY7HZF8k23aIK/BC0WuVOT3AmX2ZndncmR79T/tShWnRozcFx5x6sQls3vWnA4tiVRmp8sDmffzfcj4HycuehzRgWbLhaNswWBWAD48HUVXekYB3ipGqerx2LZEvbbkdqlrkY6MfpwoNTcogsQKBgQCLFHUx/v4z2Z4NYycql48OBhrQfK4pFqWuIGO45spfkD8C+WeCeSEal4Jjk5JQwDSPrKOUHJVJNcBPZG64Xr/KMKH0KrnzzRQPuhsi8NSUhxylY0gEj5DFJbkzksAdSEhfBLfLqIzYb3t3gr5LOZKFduGRZLz7v9IPV6HvTasoMQKBgE4nTX5RT/6ReKj9xkwrP8zJdW00FG5A9tZMudHzc6Q7a+TvdGfH6l2oq1sM3yeKj0EnBbjfL75ly/CoQJRfGfSO/8ntDUMRUAsBUhRmT4b1nCcjYo18+yWa7xV9R5T6q8E+tozz9rllMRSrZ2FGtROcKblYQGOHOBWBoaUoNCuhAoGBALskHNdD3MNQyJEPq5gUXzHXogfhbbugB2GjtoO5rDwiA0p7+34aJWCfxCzECwXE20b8e+oefoJLBnXsvkke1BAJPMb1S8AhfvOze3VLNUB0nwygb2WsAc7Vi3M04SxbZ9fI6/piE9fZgcu02kooTJHEwf9lel8fRdAmb2avuvto
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyfmOgC9X8WTTeDfEvJ/kXV53ZMu9Xh7I9SxaH6o42Y3N3hpxq4mn4bTo+dmfphWaa32FKnT4AARiEpvScIJTJETW5nxNzLRZ7ePKmAErllRTLGQ4osvGVNN4CgAnZVxCldPQpl50er7Tomg3jGQZjVZYMLeWpZ8kQnWkwyMEiYg9kj9vbVWzqWGUBHxuKZvbee1IHC06jqqYQ9G/bA6C2XXeA1RRNo+NwBy8JvZ/U3k8dRf8G2U2TWOiv2YxulG/Df8LY/bHv4zqx/owwmQdVl4OZ5BUKmGu9CkBC8D+JaNGw6176O7GlW0c2JJzNDM3m7TLasIbvPWVcH62rZRulQIDAQAB
  notify_url: http://zlptt7ddfn.52http.net/pay/alipay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
